### PR TITLE
Browscap parsing for ruby 1.9

### PR DESCRIPTION
**Pull request by gilles**
Hi,

The current version of ini file can't parse browscap.ini on ruby 1.9 because of character encoding issues. This patch takes care of it.

Thanks

### CODE REVIEW

**Comment by melkon** [comment]
Hey,

though I'm not the maintainer of this project I'd like to throw in some thoughts.

You said yourself it is an encoding issue ... and not in particular with browsercap.ini - this file just have a not working encoding. Adding a file with >20000 lines looks a little bit like cracking a nut with a sledgehammer. I guess it would be more useful if you identify the part(s) which errors and and write a test for that. You're almost doubling inifile's filesize with browsercap.ini.

Second, you're only fixing files with ISO-8859-1 encoding. Wouldn't it be wiser to generally cast the file in question to UTF-8 so there wont be any issues with different encodings than ISO-8859-1?

And again, since I'm not the maintainer, it's just my opinion.

Kind regards,
André Gawron

**Comment by gilles** [comment]
The file is as-is, downloaded from http://browsers.garykeith.com/downloads.asp, it has a working encoding:

```
$ file test/data/browscap.ini 
test/data/browscap.ini: ISO-8859 English text, with CRLF line terminators
```

The thing is ruby believes it's UTF-8:

```
File.open(@fn, 'r') do |f|
  while line = f.gets
    line = line.chomp
    puts line.encoding
  end
end
```

-> prints UTF-8

Then since it's not really UTF-8 the === comparison fails. The failing character, 'â' is encoded in ISO-8859-1 (not an ASCII char, not a subset of utf-8)

Actually this makes me thing that a better patch would be:

```
if RUBY_VERSION >= '1.9'
  line.force_encoding('ISO-8859-1')
end
```

or even better passing the file encoding as a parameter.

but you are correct, there is no standard requiring a .ini to be ISO-8859-1. Even though from wikipedia:

   \x????   Unicode character with hexadecimal codepoint corresponding to ????

would suggest ISO-8859-1 with unicode char as hex codepoints but you can't be sure.

I'm afraid that by converting the file to UTF-8 beforehand things like \x???? will be interpreted as string literals, not converted into the proper character.

I'm not quite sure what the proper solution is then...

I'll make another patch with a reduced test case and a smarter solution to handle encoding.

Thanks a lot, the mental process of answering led me to a better solution I believe, will check in soon.

--GIlles

**Comment by gilles** [comment]
Actually the new commits went automatically in the pull request... nice. Let me know what you think of this approach.

**Comment by melkon** [comment]
Thanks for clarification of the problem - and, at least for me, the new patch looks good.

I'd also implement this encoding-handling for the write-method ... and the documentation (#initialize) has to be updated properly :)

**Comment by gilles** [comment]
Good points, I'll work on that

**Comment by TwP** [comment]
Thanks for all work on encoding! I will pull in these changes and wait on the encoding for writing files before pushing a new release. Please open a new pull request when those changes are ready to go.

By the way ... I made several changes to make this work with ruby 1.8.7. And I also pulled in some other changes made by melkon. You will have a few conflicts to resolve FYI.

Blessings,
TwP

**Comment by rykr30** [comment]
Adding this stanza to my program for parsing the IMDB *.list files worked for Ruby 1.9.  My parsers did not need this for Ruby 1.8.

``` ruby
if RUBY_VERSION >= '1.9'
  line.force_encoding('ISO-8859-1')
end
```

**Pull request closed without merging**
